---
title: "CTRP simple"
output: html_document
---

```{r eval=F}
dim(x)

y=scale(sens)
# seq_len(ncol(y))
```

```{r}
b=foreach(drug_index=1:ncol(y), .combine=cbind) %dopar% {
  y_here=y[,drug_index]
  not_na=!is.na(y_here)
  y_here=y_here[not_na]
  x_here=x[not_na,]
  solve( t(x_here) %*% x_here + 0.1 * diag(ncol(x_here)), t(x_here) %*% y_here )
}  

colnames(b)=colnames(y)
      
saveRDS(b, "l2coef.rds")
```

```{r}
b=readRDS("l2coef.rds")
sv=svd(b)
sv2=irlba(b,30)

hist(sv2$u[,1]) # which features
hist(sv2$v[,1]) # which drugs. Positive on almost all: GLDS
```

```{r}
hist(sv2$u[,2]) # which features
hist(sv2$v[,2]) # which drugs. Spread around 0.
```

```{r}
feat_cutoff=3 * sqrt(1/3000)
drug_cutoff=2.5 * sqrt(1/545)
foreach(pc_index=seq_along(sv2$d), .combine = bind_rows) %do% {
  data.frame( pc_index=pc_index, 
              num_feat=sum(abs(sv2$u[,pc_index]) > feat_cutoff), 
              num_drugs=sum(abs(sv2$v[,pc_index]) > drug_cutoff) )
}
```

```{r eval=F}
require(gplots)
clustersDir="simple_clusters/"
dir.create(clustersDir)

foreach(pc_index=2:length(sv2$d)) %do% {
  clus_feats=abs(sv2$u[,pc_index]) > feat_cutoff
  clus_drugs=abs(sv2$v[,pc_index]) > drug_cutoff
  
  clus_coef=b[ clus_feats, clus_drugs ]
  
  clus_coef = clus_coef[ , !grepl( "mol/mol" , colnames(clus_coef) ) ]
  
  pdf(paste0(clustersDir,"plot",pc_index,".pdf"),width=2+.2*ncol(clus_coef),height=2+.2*nrow(clus_coef))
  heatmap.2(clus_coef, col=rev(brewer.pal(21,"RdBu")), trace="none", key=F, dendrogram="none", lwi=c(0.01,1), lhei=c(0.01,1), margins=c(10,8))
  dev.off()
  
  # mean(clus_coef^2) / mean(b^2)
  
}



```

```{r}
hinge=function(g) { ifelse(g > 0, g, 0) }
soft_threshold=function(g, threshold=1) {
  res=sign(g) * hinge(abs(g) - threshold ) 
}
plot(function(...) soft_threshold(..., threshold = 2),-5,5)
```

```{r}
B=soft_threshold(sv2$u[,2:30], threshold=feat_cutoff) %>% t()
factor_loadings=soft_threshold(sv2$v[,2:30], threshold=drug_cutoff)

factors=foreach(cell_index=1:nrow(y), .combine = cbind) %dopar% {
  y_here=y[cell_index,]
  to_keep=!is.na(y_here)
  y_here=y_here[to_keep]
  fl_here=factor_loadings[to_keep,]
  solve( t(fl_here) %*% fl_here + 0.1 * diag(ncol(fl_here)), t(fl_here) %*% y_here )
}
```

```{r}
require(Matrix)
saveRDS(list(B=Matrix(B, sparse = TRUE), factors=factors, factor_loadings=Matrix(factor_loadings, sparse = TRUE)), file="ctrp_simple_init.rds")
```

